### ISSUE TITLE
error with nodes compiled against other nodes 

### ISSUE THREAD

**Issue by jossdom** [atom/node-keytar#116]
hi guys i am trying to figure out how to resolve this but nothing works i tried nom rebuild and electron rebuilds you name it i have tried it this is the error code 
Error: The module '/usr/local/lib/node_modules/ls-psvr-encoder/node_modules/get-cursor-position/build/Release/pos.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/ls-psvr-encoder/node_modules/get-cursor-position/index.js:1:74)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

**Comment by shiftkey** [comment]
@jossdom it's not clear to me that this issue is related to `node-keytar`. I recommend contacting the authors of [`get-cursor-position`](https://github.com/bubkoo/get-cursor-position).
