### ISSUE TITLE
domain.enter() is not a function

### ISSUE THREAD

**Issue by wbrickner** [atom/node-keytar#138]
Operating System: `OS X 10.13.4 High Sierra`

1) Fresh install (`npm install --save keytar`)
2) Start node REPL (`node`)
3)
```
> const keytar = require("keytar")
undefined
> keytar.setPassword("MyService", "MyAccount", "MySecretPassword").then((result) => console.log(result))
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events:
      [Object: null prototype] {
        removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [] } }
> domain.js:119
    domain.enter();
           ^

TypeError: domain.enter is not a function
    at topLevelDomainCallback (domain.js:119:12)
```

At which point node crashes with the above output.
Using the newest version of node (v11.2.0), although the issue also occurs on v10.

**Comment by wjhir** [comment]
I'm also getting this error on Windows 10 / node v10.11.0 / keytar v4.3.0.
```
> require('keytar').getPassword('service', 'account').then(console.log, console.error)
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events:
      { removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [] } }
> domain.js:120
    domain.enter();
           ^

TypeError: domain.enter is not a function
    at topLevelDomainCallback (domain.js:120:12)
```

**Comment by shiftkey** [comment]
Sounds like we need to address the `nan` deprecations to support newer versions of V8 e.g. https://github.com/aerospike/aerospike-client-nodejs/issues/254 and https://github.com/aerospike/aerospike-client-nodejs/pull/255

**Comment by shiftkey** [comment]
I've not been able to reproduce this as of Node 10.15.3 and keytar 4.9.0 (on macOS 10.14.5 at least):

```
> const keytar = require("keytar")
undefined
> keytar.setPassword("MyService", "MyAccount", "MySecretPassword").then((result) => console.log(JSON.stringify(result)))
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events:
      [Object: null prototype] {
        removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [] } }
> undefined
```

Feel free to add more context here if you spot anything out of the ordinary.
