### ISSUE TITLE
Building 32-bit version getting error: size of array ‘_GStaticAssertCompileTimeAssertion_0’ is negative

### ISSUE THREAD

**Issue by smoak** [atom/node-keytar#142]
Trying to compile `4.2.0` 32-bit on my machine and I am getting a mysterious error:

```bash
$ node-gyp build --arch=ia32

...SNIPPED...

CXX(target) Release/obj.target/keytar/src/keytar_posix.o
In file included from /usr/lib/glib-2.0/include/glibconfig.h:9,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/libsecret-1/libsecret/secret.h:18,
                 from ../src/keytar_posix.cc:6:
/usr/include/glib-2.0/glib/gtypes.h: In function ‘gboolean _GLIB_CHECKED_ADD_U64(guint64*, guint64, guint64)’:
/usr/include/glib-2.0/glib/gmacros.h:181:29: error: size of array ‘_GStaticAssertCompileTimeAssertion_0’ is negative
   __attribute__((__unused__))
                             ^
/usr/include/glib-2.0/glib/gmacros.h:277:120: note: in expansion of macro ‘G_GNUC_UNUSED’
 #define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1] G_GNUC_UNUSED
                                                                                                                        ^~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gtypes.h:423:3: note: in expansion of macro ‘G_STATIC_ASSERT’
   G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));
   ^~~~~~~~~~~~~~~
make: *** [keytar.target.mk:107: Release/obj.target/keytar/src/keytar_posix.o] Error 1
make: Leaving directory '/tmp/node-keytar-4.2.0/build'
gyp ERR! build error
```

I have lib32-glibc and lib32-glib2 installed on my system, so I'm not sure where to go from here. Any ideas?

**Comment by shiftkey** [comment]
It's not clear to me which version of Node you are building against here

**Comment by smoak** [comment]
Here is what I used:

node -v v8.11.4
node-gyp -v v3.8.0
npm -v 6.5.0

**Comment by sentialx** [comment]
@shiftkey For me it's also not working. I'm using GitHub Actions with `ubuntu-latest` 
(Ubuntu 18.04) https://github.com/wexond/desktop/runs/453365617
The config can be found there: https://github.com/wexond/desktop/blob/electron-9/.github/workflows/build.yml

**Comment by sentialx** [comment]
Is there a workaround for this? It's really blocking my development due to CI failures: https://github.com/wexond/desktop/pull/391

**Comment by shiftkey** [comment]
> Electron 9.0.0-beta.2 (there are no prebuilt binaries)

@sentialx please try out #252 as I was able to add support for Electron 9 beta 2 with version `5.3.0`, and I didn't encounter issues building on Linux.

**Comment by sentialx** [comment]
@shiftkey I tried out `5.3.0` and it throwed me the same errors.

```
errorOut=prebuild-install WARN install No prebuilt binaries found (target=9.0.0-beta.2 runtime=electron arch=ia32 libc= platform=linux)
    gyp info it worked if it ends with ok
    gyp info using node-gyp@5.0.5
    gyp info using node@12.16.1 | linux | x64
    gyp info find Python using Python version 2.7.17 found at "/usr/bin/python"
    gyp http GET https://electronjs.org/headers/v9.0.0-beta.2/node-v9.0.0-beta.2.tar.gz
    gyp http 200 https://electronjs.org/headers/v9.0.0-beta.2/node-v9.0.0-beta.2.tar.gz
    gyp http GET https://electronjs.org/headers/v9.0.0-beta.2/SHASUMS256.txt
    gyp http 200 https://electronjs.org/headers/v9.0.0-beta.2/SHASUMS256.txt
    gyp info spawn /usr/bin/python
    gyp info spawn args [
    gyp info spawn args   '/opt/hostedtoolcache/node/12.16.1/x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
    gyp info spawn args   'binding.gyp',
    gyp info spawn args   '-f',
    gyp info spawn args   'make',
    gyp info spawn args   '-I',
    gyp info spawn args   '/home/runner/work/desktop/desktop/node_modules/keytar/build/config.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/opt/hostedtoolcache/node/12.16.1/x64/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/home/runner/.electron-gyp/9.0.0-beta.2/include/node/common.gypi',
 gyp info spawn args   '-Dlibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=/home/runner/.electron-gyp/9.0.0-beta.2',
    gyp info spawn args   '-Dnode_gyp_dir=/opt/hostedtoolcache/node/12.16.1/x64/lib/node_modules/npm/node_modules/node-gyp',
    gyp info spawn args   '-Dnode_lib_file=/home/runner/.electron-gyp/9.0.0-beta.2/<(target_arch)/node.lib',
    gyp info spawn args   '-Dmodule_root_dir=/home/runner/work/desktop/desktop/node_modules/keytar',
    gyp info spawn args   '-Dnode_engine=v8',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.'
    gyp info spawn args ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    In file included from /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h:9:0,
                     from /usr/include/glib-2.0/glib/gtypes.h:32,
                     from /usr/include/glib-2.0/glib/galloca.h:32,
                     from /usr/include/glib-2.0/glib.h:30,
                     from /usr/include/libsecret-1/libsecret/secret.h:18,
                     from ../src/keytar_posix.cc:6:
    /usr/include/glib-2.0/glib/gtypes.h: In function ‘gboolean _GLIB_CHECKED_ADD_U64(guint64*, guint64, guint64)’:
    /usr/include/glib-2.0/glib/gmacros.h:145:29: error: size of array ‘_GStaticAssertCompileTimeAssertion_0’ is negative
       __attribute__((__unused__))
 /usr/include/glib-2.0/glib/gtypes.h:423:3: note: in expansion of macro ‘G_STATIC_ASSERT’
       G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));
       ^~~~~~~~~~~~~~~
    make: *** [Release/obj.target/keytar/src/keytar_posix.o] Error 1
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/opt/hostedtoolcache/node/12.16.1/x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    gyp ERR! System Linux 5.0.0-1031-azure
    gyp ERR! command "/opt/hostedtoolcache/node/12.16.1/x64/bin/node" "/opt/hostedtoolcache/node/12.16.1/x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /home/runner/work/desktop/desktop/node_modules/keytar
    gyp ERR! node -v v12.16.1
    gyp ERR! node-gyp -v v5.0.5
    gyp ERR! not ok 
    error Command failed with exit code 1.
    
                    command=/opt/hostedtoolcache/node/12.16.1/x64/bin/node /usr/share/yarn/bin/yarn.js run install
                    workingDir=/home/runner/work/desktop/desktop/node_modules/keytar
```

**Comment by shiftkey** [comment]
Ah, I didn't notice you were looking for 32-bit prebuilds.

If you want that to happen, please submit a PR to add the version to this line:

https://github.com/atom/node-keytar/blob/edbc3a49d1decab2bd1e0e6372fa2b5bed1844de/package.json#L40

If it all works fine, I can cut a new release.

**Comment by sentialx** [comment]
Yeah, but what if I wanted to build a version of Electron that you don't support yet?

**Comment by shiftkey** [comment]
Recent versions of Electron ship a stable ABI between major versions - so the betas should work like a stable release until they're ready (which is what I did in #252 but just for the 64-bit version of Electron).

This has worked fine for us for the last few releases - once they go stable we just drop the `-beta.X` prefix and ship an update.

**Comment by shiftkey** [comment]
@smoak `5.4.0` has been published.

I'm going to close this out because I want users to be using `prebuild` binaries to keep things simple, and we should be up-to-date with the supported versions of NodeJS and Electron https://github.com/atom/node-keytar#supported-versions. I don't have the bandwidth to troubleshoot issues with the compiler toolchain.

**Comment by sentialx** [comment]
@shiftkey How to add support for Electron nightly?

**Comment by shiftkey** [comment]
@sentialx there's nothing limiting this being used in a `electron-nightly` release as long as it's the same Node ABI version underneath as what's being prebuilt. If not, it'll fall back to building from source.

If you're asking about prebuild support for Electron 10 nightlies then those are probably a newer Node ABI not currently supported in https://github.com/lgeiger/node-abi/. Until those land in an `electron` package (that's the runtime that Node looks for) with an update `node-abi` package for the new ABI version it's not in a state that I'd feel confident in supporting.
