### ISSUE TITLE
Can't set service password without an account

### ISSUE THREAD

**Issue by wegylexy** [atom/node-keytar#169]
`findPassword()` can find service password, but `setPassword()` throws `Account is required.`
```javascript
keytar.setPassword("My Service", null, "access_token"); // should save the token in Windows Vault
console.log(await keytar.findPassword("My Service")); // this works when the token is already in Windows Vault
```

**Comment by shiftkey** [comment]
I believe this is caused by the validation in the client (before calling the native API):

https://github.com/atom/node-keytar/blob/99d30585f5ae86153f71317ce24978fa9cede199/lib/keytar.js#L33-L39

**Comment by wegylexy** [comment]
if I `require` that directly, there is still a `/`
```javascript
const kn = require("keytar/build/Release/keytar.node");
kn.setPassword("My Service", null, "access_token"); // results in "MyService/null" as target
kn.setPassword("My Service", "", "access_token"); // results in "MyService/" as target
`

**Comment by cullub** [comment]
Can reproduce on Windows 10 2004.  

```
keytar.setPassword('myService', '', 'MyNewPassword');
```

Throws:

```
(node:5416) UnhandledPromiseRejectionWarning: Error: Account is required.
    at checkRequired (C:\Users\me\Desktop\myProject\node_modules\keytar\lib\keytar.js:5:11)
    at Object.setPassword (C:\Users\me\Desktop\myProject\node_modules\keytar\lib\keytar.js:19:5)
    at Module.update (file:///C:/Users/me/Desktop/myProject/server/updateConfig/config.js:141:16)
    at file:///C:/Users/me/Desktop/myProject/server/updateConfig/configController.js:42:27
    at Layer.handle [as handle_request] (C:\Users\me\Desktop\myProject\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\me\Desktop\myProject\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\me\Desktop\myProject\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\me\Desktop\myProject\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\me\Desktop\myProject\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\me\Desktop\myProject\node_modules\express\lib\router\index.js:335:12)
```

**Comment by wegylexy** [comment]
There should be a way to omit the account and the slash.

**Comment by xmedeko** [comment]
I would like set password without account, too. But only if it's possible on all platforms (Windows, Linux, MacOSX).

**Comment by wegylexy** [comment]
Never mind, we decided to move away from the OS vault.
