### ISSUE TITLE
Install fails on Ubuntu Trusty / Unity

### ISSUE THREAD

**Issue by naholyr** [atom/node-keytar#18]
Hello, I guess this is related to #7 but here install is failing whatever I do :(

This keeps me from building Atom from sources for instance.

```
> keytar@2.1.0 install /home/nchambrier/Projects/Perso/atom/apm/node_modules/keytar
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
Package gnome-keyring-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gnome-keyring-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gnome-keyring-1' found
gyp: Call to 'pkg-config --libs-only-l gnome-keyring-1' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/nchambrier/.nvm/versions/node/v0.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.13.0-45-generic
gyp ERR! command "node" "/home/nchambrier/.nvm/versions/node/v0.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nchambrier/Projects/Perso/atom/apm/node_modules/keytar
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.13.0-45-generic
npm ERR! argv "/home/nchambrier/.nvm/versions/node/v0.12.0/bin/node" "/home/nchambrier/.nvm/versions/node/v0.12.0/bin/npm" "i" "keytar"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! keytar@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
```

**Comment by Pouja** [comment]
It seems that you miss the `libgnome-keyring-dev` package as noted in the README.

**Comment by Guria** [comment]
@Pouja have installed `libgnome-keyring-dev` still have `node-gyp rebuild` error

**Comment by havenchyk** [comment]
I found solution here https://github.com/atom/atom/issues/1948#issuecomment-42344415.

```
sudo apt-get install libgnome-keyring-dev
sudo npm config set python /usr/bin/python2 -g
```

**Comment by havenchyk** [comment]
@naholyr did you solve it? Works fine with library from the README

**Comment by Guria** [comment]
it was also required to run `sudo apt-get install node-gyp` for me as well

**Comment by NightBrownie** [comment]
`sudo apt-get install libsecret-1-dev`
solved the issue during electron-rebuild for me

**Comment by shiftkey** [comment]
To build `keytar` on Linux you need to have these dependencies available: https://github.com/atom/node-keytar#on-linux

To use this as part of an application on Linux you need to also have installed a program that can interop with libsecret - `gnome-keyring` is a popular example that's available for plenty of distributions.
