### ISSUE TITLE
electron 6 support

### ISSUE THREAD

**Issue by pjebs** [atom/node-keytar#215]
I upgrade to electron 6.

My electron application stopped working:

```
Uncaught Exception:
Error: Module did not self-register.
    at process.func (electron/js2c/asar.js:155:31)
    at process.func [as dlopen] (electron/js2c/asar.js:155:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:155:31)
    at Object.func [as .node] (electron/js2c/asar.js:155:31)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/x/Developer/y/desktop-app/node_modules/keytar/lib/keytar.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at /Users/x/Developer/y/desktop-app/app/main.js:140176:13
    at Object.<anonymous> (/Users/x/Developer/y/desktop-app/app/main.js:140197:5)
    at Object.<anonymous> (/Users/x/Developer/y/desktop-app/app/main.js:140571:4)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at loadApplicationPackage (/Users/x

```

**Comment by pjebs** [comment]
npm:
dep:
`    "keytar": "^5.0.0-beta.0",`

**Comment by pjebs** [comment]
@shiftkey

**Comment by shiftkey** [comment]
@pjebs this is a generic error that usually suggests there's a mismatch between the target platform the native module is built against and the version of Electron being used.

It's not clear to me which OS you're running on (macOS?) but I'd recommend reverting to [`v4.13.0`](https://github.com/atom/node-keytar/releases/tag/v4.13.0) which has prebuild targets for all supported platforms, unless you can put together a full repro of the issue that you can share.

**Comment by pjebs** [comment]
i'm on mac.
I commented out keytar code and removed keytar dependency and my electron application launches.

**Comment by shiftkey** [comment]
> I commented out keytar code and removed keytar dependency and my electron application launches.

This doesn't surprise me, but it's also not clear to me how you're building the native modules (I gather that's what's happening, as I can't see whether the `prebuild-install` step is working as expected when you run `npm install`).

Without a prebuild binary, it's going to use the native toolchain to try and build the native module from source, and unless you're using something like `electron-prebuild` or a well-configured `.npmrc` I wonder whether you're building the native module against the version of `node` you have installed locally (which would explain the mismatch, if you're running a version of Node that's not Node 12).

**Comment by pjebs** [comment]
I changed to `4.13.0` and same issue.

I'm not doing any prebuilding. I'm just changing dependency version in npm file and then running `npm install`. 

Then I am running the electron dev application with `electron .` (but via npm).

I assumed npm versions would already have prebuilt binaries because this is what I've always done with electron 4-5.

**Comment by shiftkey** [comment]
> I assumed npm versions would already have prebuilt binaries because this is what I've always done with electron 4-5.

These already exist (`v73` is the version associated with Electron 6,  based on [what's in node-abi](https://github.com/lgeiger/node-abi/blob/master/index.js#L73)):

<img width="424" src="https://user-images.githubusercontent.com/359239/63228497-2e8c1e00-c1ca-11e9-8e95-609394db885e.png">

I was able to reproduce this issue on my side, and I don't believe this is anything I can fix in keytar.

What I want to see is the output this command from your project:

```
$ npm install --save electron@4.13.0 --verbose
```

I did this with `electron-quick-start` (which is currently on Electron 6.0.2) and I saw this output:

```
npm info lifecycle keytar@4.13.0~install: keytar@4.13.0

> keytar@4.13.0 install /Users/shiftkey/src/electron-quick-start/node_modules/keytar
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 5.3.0
prebuild-install info looking for cached prebuild @ /Users/shiftkey/.npm/_prebuilds/5e5845-keytar-v4.13.0-node-v64-darwin-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ /Users/shiftkey/.npm/_prebuilds/5e5845-keytar-v4.13.0-node-v64-darwin-x64.tar.gz
prebuild-install info unpack resolved to /Users/shiftkey/src/electron-quick-start/node_modules/keytar/build/Release/keytar.node
prebuild-install info unpack required /Users/shiftkey/src/electron-quick-start/node_modules/keytar/build/Release/keytar.node successfully
prebuild-install info install Successfully installed prebuilt binary!
```

While this seems to have worked, it's chosen `v64` for the prebuild module (because I was running this in Node 10). I went and required `keytar` in `electron-quick-start`:

```diff
diff --git a/main.js b/main.js
index 3508c8e..d19ad8a 100644
--- a/main.js
+++ b/main.js
@@ -12,7 +12,8 @@ function createWindow () {
     width: 800,
     height: 600,
     webPreferences: {
-      preload: path.join(__dirname, 'preload.js')
+      preload: path.join(__dirname, 'preload.js'),
+      nodeIntegration: true,
     }
   })
diff --git a/renderer.js b/renderer.js
index 901d75e..a3e9c60 100644
--- a/renderer.js
+++ b/renderer.js
@@ -1,3 +1,4 @@
 // This file is required by the index.html file and will
 // be executed in the renderer process for that window.
 // All of the Node.js APIs are available in this process.
+const keytar = require('keytar')
```

And then I ran the `npm start` script to launch the app. While it seems fine I see your error in the dev tools:

<img width="819" alt="Screen Shot 2019-08-18 at 3 19 20 PM" src="https://user-images.githubusercontent.com/359239/63228605-d0f8d100-c1cb-11e9-9c9d-ac1a0af0c7fd.png">

And this comes back to that `v64/v73` mismatch from earlier.

To address this, I'd recommend using [`electron-rebuild`](https://github.com/electron/electron-rebuild) in your project.

**Comment by pjebs** [comment]
How can the mismatch be fixed so it's automatic?( No need for electron rebuild)

**Comment by shiftkey** [comment]
> How can the mismatch be fixed so it's automatic?( No need for electron rebuild)

Add an `.npmrc` file alongside your `package.json` file - [this is what we do inside GitHub Desktop](https://github.com/desktop/desktop/blob/development/app/.npmrc) -  it requires updating when the version of Electron updates (so it's not fully automatic) but I'm pretty happy with it.

**Comment by pjebs** [comment]
what's the content of the `.npmrc` file?

**Comment by shiftkey** [comment]
@pjebs I linked to an example in the previous comment, but here it is again:

```
runtime = electron
disturl = https://atom.io/download/electron
target = 6.0.0
arch = x64
```

Replace the value of `target` with your current version of Electron. There's a limitation here that `arch` must be set, so building native modules for multiple architectures is not supported by this approach, and why `electron-rebuild` is still recommended.

**Comment by pjebs** [comment]
thank you @shiftkey

**Comment by pjebs** [comment]
I just used https://github.com/electron/electron-rebuild and ran `$(npm bin)/electron-rebuild`

**Comment by Raj123456788** [comment]
Hey @pjebs : I am seeing the same error can you please explain what did you do to get rid of it? what you mean by (npm bin)/electron-rebuild?

**Comment by pjebs** [comment]
Install `electron-rebuild` as a devDependency and then run `$(npm bin)/electron-rebuild`

**Comment by Raj123456788** [comment]
I am getting same error for an addon  that I am trying to access. Any help is appreciated. 
![image](https://user-images.githubusercontent.com/16295521/87446102-b8e12b80-c5ad-11ea-9d91-6f33ec637eed.png)

**Comment by vbarbarosh** [comment]
I have this error after installing `dbus` npm module. The fix was:

    npm install --save-dev electron-rebuild
    `npm bin`/electron-rebuild

In order to not call `electron-rebuild` after each install, I added the following lines to `package.json` file:

    "scripts": {
      [...]
      "postinstall": "electron-rebuild"
    },

**Comment by muffinista** [comment]
OK, thanks. Can you run this in that repo:

```
$(npm bin)/electron-builder install-app-deps
```

And send me the output? Assuming there aren't any errors, can you then run whatever command you're running which is causing the self-register error, and also let me know what that command is? I'm able to clone, build, and run this app without any apparent issues.
