### ISSUE TITLE
keytar threads using libsecret concurrently cause an abort in libgcrypt

### ISSUE THREAD

**Issue by mzabaluev** [atom/node-keytar#283]
### Prerequisites

**Not done:** I have not run atom to report an environment-specific problem that occurs in a different Electron-based application using keytar as a component.

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Visual Studio Code experiences random crashes when run in [a Flatpak app](https://github.com/flathub/com.visualstudio.code) on Linux. See more discussion in https://github.com/microsoft/vscode/issues/99725

### Steps to Reproduce

1. Install the `com.visualstudio.code/x86_64/stable` Flatpak app version 1.46.0 or greater from Flathub.
2. Run the app with `flatpak run com.visualstudio.code/x86_64/stable --crash-reporter-directory=$HOME --verbose`. May need to repeat until the application freezes shortly after startup.
3. Analyze the minidump (`*.dmp`) file in `$HOME/'VSCode Crashes'` (may not be created after every freezy startup) using steps listed [here](https://github.com/microsoft/vscode/wiki/Native-Crash-Issues) with possible assistance of a script given in https://github.com/microsoft/vscode/issues/99725#issuecomment-643194105 to generate symbol files for the dynamic libraries.

**Expected behavior:**

The app starts up successfully and is responsive every time.

**Actual behavior:**

The application freezes, a crash may be reported by the crash handler of the OS.
A message appears in the output:

```
fatal error in libgcrypt, file ../../src/visibility.c, line 1361, function gcry_create_nonce: called in non-operational state
```

Eventually, a `[VS Code]: detected unresponsive` error message appears in the output after the application fails to respond to UI input.

In the crash report, two keytar threads can be seen calling into libsecret with the stacks going down into libgcrypt.

**Reproduces how often:**

50-90%

#### Visual Studio Code

Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:04.923Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.6.16-300.fc32.x86_64

#### Flatpak app

```
          ID: com.visualstudio.code
         Ref: app/com.visualstudio.code/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.46.0-1591780013
     License: LicenseRef-proprietary=https://code.visualstudio.com/license
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 3,8 MB
     Runtime: org.freedesktop.Sdk/x86_64/19.08
         Sdk: org.freedesktop.Sdk/x86_64/19.08

      Commit: 362b9a2d110c969b3bf5365ff3386c193745358573c7a7240ebb18088684505f
      Parent: 1cf4ab831b0bacb7b7a198c16526d7504b57ab0d4c10f88b8b8cce0fa845ea35
     Subject: Update code.deb to 1.46.0-1591780013 (5a4c2f23)
        Date: 2020-06-11 18:50:51 +0000
```

### Additional Information

A [stack trace](https://github.com/atom/node-keytar/files/4771804/stack.txt) collected using the steps outlined above.

**Comment by mzabaluev** [comment]
GDB assisted by `flatpak-coredumpctl`, lacking the debug information of the app, can only decipher stacks of some of the threads, but it provides a clue about what keytar is doing: 

```
#17 0x00007fc744d0418a in secret_password_lookup_sync (schema=0x7fc744f40900 <keytar::(anonymous namespace)::schema>, cancellable=0x0, error=0x7fc74d3efb20) at ../libsecret/secret-password.c:884
#18 0x00007fc744d3ead0 in keytar::GetPassword(std::string const&, std::string const&, std::string*, std::string*) () at /app/extra/vscode/resources/app/node_modules.asar.unpacked/keytar/build/Release/keytar.node
#19 0x00007fc744d39b60 in GetPasswordWorker::Execute() () at /app/extra/vscode/resources/app/node_modules.asar.unpacked/keytar/build/Release/keytar.node
```

**Comment by mzabaluev** [comment]
It's basically a house of cards in libsecret and the services it talks to: https://gitlab.gnome.org/GNOME/libsecret/-/issues/48

**Comment by mzabaluev** [comment]
The immediate problem is localized in libsecret and a fix is available.
