### ISSUE TITLE
Issue with 6.0.1 and node-gyp on Windows

### ISSUE THREAD

**Issue by keithslater** [atom/node-keytar#297]
### Description

Having issues getting 6.0.1 to install in electron 9.1.1 on Windows 10. I've tried a lot of different versions of python and windows build tools. The end result is always something like:

```c:\users\keithslater\documents\code\desktop-application\node_modules\keytar\src\main.cc(1): fatal error C1083: Cannot open include file: 'napi.h': No such file or directory [C:\Users\keithslater\Documents\CODE\desktop-application\node_modules\keytar\build\keytar.vcxproj]
c:\users\keithslater\documents\code\desktop-application\node_modules\keytar\src\async.cc(4): fatal error C1083: Cannot open include file: 'napi.h': No such file or directory [C:\Users\keithslater\Documents\CODE\desktop-application\node_modules\keytar\build\keytar.vcxproj]
```

Currently when it runs it is using this setup

```gyp info using node-gyp@5.1.0
gyp info using node@12.18.2 | win32 | x64
gyp info find Python using Python version 2.7.15 found at "C:\Users\keithslater\.windows-build-tools\python27\python.exe"
gyp info find VS using VS2017 (15.9.28307.1216) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
```

But I've also tried python 3 and different versions of VS build tools (with different components enabled). I'm not sure why it uses that version of node-gyp, I've tried to force it to use newer versions but it doesn't seem to want to. 

### Steps to Reproduce

1. Install keytar 6.0.1 on Windows
2. Run `yarn install`

No issues with 5.6.0.

**Comment by briermay** [comment]
maybe its yarn ? I don't use yarn as I have a lot of problems with it especially on larger files it likes to complain I have network issues which I have Gigabit Fibre internet and no issues. I just installed keytar today via npm i keytar and had 0 problems installing it on windows. I am using the latest 2004 (build 19041.508) version of windows also so no idea if thats making a difference

**Comment by dennisameling** [comment]
Having the same issue on Windows arm64:

```
error C:\repos\desktop\app\node_modules\keytar: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments:
Directory: C:\repos\desktop\app\node_modules\keytar
Output:
prebuild-install WARN install No prebuilt binaries found (target=9.3.1 runtime=electron arch=arm64 libc= platform=win32)

C:\repos\desktop\app\node_modules\keytar>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.13.0 | win32 | arm64
gyp info find Python using Python version 3.8.5 found at "C:\Python38\python.exe"
gyp info find VS using VS2019 (16.7.30330.147) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
```
results in:
```
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  async.cc
  main.cc
  keytar_win.cc
  win_delay_load_hook.cc
C:\repos\desktop\app\node_modules\keytar\src\main.cc(1,10): fatal error C1083: Cannot open include file: 'napi.h': No such file or directory [C:\repos\desktop\app\node_modules\keytar\build\keytar.vcxproj]
C:\repos\desktop\app\node_modules\keytar\src\async.cc(4,10): fatal error C1083: Cannot open include file: 'napi.h': No such file or directory [C:\repos\desktop\app\node_modules\keytar\build\keytar.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\repos\desktop\app\node_modules\keytar
gyp ERR! node -v v14.13.0
```

I'm running into this while trying to add arm64 support to GitHub Desktop.
When I checkout keytar locally, add prebuild Electron arm64 binaries, then run `yarn link keytar`, the installation succeeds.

**Comment by dennisameling** [comment]
@keithslater this PR should fix the issue: https://github.com/atom/node-keytar/pull/325
