### ISSUE TITLE
Trouble loading keytar on Ubuntu 12 after rebuilding for Electron app

### ISSUE THREAD

**Issue by joeferraro** [atom/node-keytar#30]
Hi, I am successfully building an Electron app that requires keytar on OSX and Windows (32 & 64-bit), however on Linux (Ubuntu 12), I'm having some trouble. 

During my Linux build, `npm install` and `electron-rebuild` both complete without issue (seemingly), however, when I install the app on another Linux machine, navigate to the app's root, start a node shell and try to load the module, I get:

```
Error: Module version mismatch. Expected 14, got 44.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/<path-to-app>/resources/app/node_modules/keytar/lib/keytar.js:4:12)
    at Object.<anonymous> (/home/josephferraro/<path-to-app>/resources/app/node_modules/keytar/lib/keytar.js:58:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

Fully understand this issue could have just as well been posted over at the electron-rebuild project, but figured I'd start here.

Cheers

Edit: I've tried to build via node 0.12.7 and iojs 3.1.0, Electron v0.30.4

**Comment by joeferraro** [comment]
not happening for me anymore, not sure what changed, unfortunately

**Comment by paulcbetts** [comment]
Once you run `electron-rebuild`, those modules only work in Electron, they won't work in your system's node. Use DevTools to do what you wanted to do in node console
