### ISSUE TITLE
Install fails on Windows 8

### ISSUE THREAD

**Issue by iamdriz** [atom/node-keytar#32]
I get this error when trying to install this module on a Windows 8 machine:

~~~
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

H:\>c:

C:\>cd C:\AVTech\_keychain

C:\AVTech\_keychain>npm install keytar
|
> keytar@3.0.0 install C:\AVTech\_keychain\node_modules\keytar
> node-gyp rebuild


C:\AVTech\_keychain\node_modules\keytar>if not defined npm_config_node_gyp (node
 "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\
node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\AVTech\_keychain\node_modules\keytar
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "keytar"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! keytar@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keytar@3.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\AVTech\_keychain\npm-debug.log

C:\AVTech\_keychain>
~~~

Does this mean you need to have Python installed before you can use this module? It doesn't mention Python as a dependency in the documentation here: https://github.com/atom/node-keytar#installing

**Comment by 50Wliu** [comment]
Yeah, you have to have Python 2.7 installed - it's a requirement for node-gyp.  Feel free to create a PR that updates the documentation!

**Comment by iamdriz** [comment]
@50Wliu Why does this require node-gyp? I thought that was only used to build node native add-ons not run them once they have been built.

**Comment by 50Wliu** [comment]
@iamdriz Correct.  node-keytar contains native files, though, and in order to install keytar you'll need to build those native files which requires node-gyp.

**Comment by iamdriz** [comment]
@50Wliu So once I've got the module in my app I won't need Python on the machine I run the app on?

**Comment by 50Wliu** [comment]
I'm pretty sure you don't.

**Comment by iamdriz** [comment]
@50Wliu Installed Python and looked to be working, but then failed:

~~~
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

H:\>c:

C:\>cd C:\AVTech\_storage

C:\AVTech\_storage>npm install keytar
-
> keytar@3.0.0 install C:\AVTech\_storage\node_modules\keytar
> node-gyp rebuild


C:\AVTech\_storage\node_modules\keytar>if not defined npm_config_node_gyp (node
"C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\n
ode-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\AVTech\_storage\node_modules\keytar\build\keytar.vcxproj(20,3): error MSB401
9: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm
 that the path in the <Import> declaration is correct, and that the file exists
 on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\AVTech\_storage\node_modules\keytar
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "keytar"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! keytar@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keytar@3.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\AVTech\_storage\npm-debug.log

C:\AVTech\_storage>
~~~

**Comment by iamdriz** [comment]
@50Wliu Turns out you also need to install Visual Studio

**Comment by 50Wliu** [comment]
@iamdriz Sorry, I didn't see your other comment :(.
The requirements for running node-gyp are here: https://github.com/nodejs/node-gyp#installation (just skip to the Windows section).

**Comment by ankur-sardar** [comment]
Any solution for your error? @50Wliu . I have installed VS15, still showing the same error
