### ISSUE TITLE
build fails on os x with dev tools < v.7

### ISSUE THREAD

**Issue by lucidNTR** [atom/node-keytar#33]
either fix or just update the readme...

**Comment by andremaha** [comment]
Same here.

**Comment by andremaha** [comment]
```
➜  ~  npm install -g keytar

> keytar@3.0.0 install /usr/local/lib/node_modules/keytar
> node-gyp rebuild

  CXX(target) Release/obj.target/keytar/src/main.o
  CXX(target) Release/obj.target/keytar/src/keytar_mac.o
  SOLINK_MODULE(target) Release/keytar.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/keytar.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/Cellar/node/4.2.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/keytar
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/4.2.1/bin/node" "/usr/local/bin/npm" "install" "-g" "keytar"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! keytar@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
```

**Comment by orlin** [comment]
This also fails with Command Line Tools v7.1 on Yosemite.  Using node `v4.2.x`.  Because of it I can't install atom-package-manager (`apm`) either.

**Comment by shiftkey** [comment]
Closing this out as stale. Node 6 is the minimum supported version for `keytar` and and our Travis builds use XCode `9.4.1`.
