### ISSUE TITLE
Error with node 5.1.0 on Windows

### ISSUE THREAD

**Issue by ocombe** [atom/node-keytar#34]
I just updated to node 5.1.0 and I get the following error:

```sh
module.js:450
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:450:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Olivier\AppData\Roaming\npm\node_modules\semantic-release-cli\node_modules\keytar\lib\keytar.js:4:12)
    at Object.<anonymous> (C:\Users\Olivier\AppData\Roaming\npm\node_modules\semantic-release-cli\node_modules\keytar\lib\keytar.js:58:4)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
```

I don't know if it's specific to Windows, but it was working fine with node 4.0.x :-/

**Comment by paulcbetts** [comment]
node-gyp rebuild

**Comment by havenchyk** [comment]
@ocombe just rebuild it. I think this issue can be closed. /cc @paulcbetts

**Comment by ocombe** [comment]
Yes sorry, this was an error of cache and a matter of rebuilding the lib (since I changed the node version).
