### ISSUE TITLE
Module version mismatch

### ISSUE THREAD

**Issue by havenchyk** [atom/node-keytar#35]
Hi, I've got this error on Ubuntu 14.04. 
I'm trying to integrate this module with electron application.

```
> electron .

App threw an error when running [Error: Module version mismatch. Expected 47, got 14.]
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Module version mismatch. Expected 47, got 14.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:153:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:153:20)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/myfolder/src/electron/node_modules/keytar/lib/keytar.js:4:12)
    at Object.<anonymous> (/home/myfolder/src/electron/node_modules/keytar/lib/keytar.js:58:4)
```

I use an old version of node.js (0.12) with an old (2.7.4) and latest (3) npm.

**Comment by havenchyk** [comment]
I've tried to run it on electron, so for electron I have to rebuild the module with `electron-rebuild`, missed it.
