### ISSUE TITLE
Can't build keytar with Electron Windows

### ISSUE THREAD

**Issue by Brouilles** [atom/node-keytar#399]
I'm on Windows 10, with Visual Studio 2019 community installed (and the C++ toolchain).
Python 3.9 from the MS Store and NodeJS v14.17.1. When I try to run `npm i` I have this error. Any idea?

```
> electron-rebuild

⠏ Building module: keytar, Completed: 0gyp info find Python using Python version 3.9.5 found at "C:\Users\gaeta\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe"
⠦ Building module: keytar, Completed: 0gyp info find VS using VS2019 (16.10.31410.357) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\gaeta\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\gaeta\\Git\\dezeiraud-play\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\gaeta\\Git\\dezeiraud-play\\node_modules\\keytar\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\gaeta\\Git\\dezeiraud-play\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\gaeta\\.electron-gyp\\13.1.4\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\gaeta\\.electron-gyp\\13.1.4',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\gaeta\\Git\\dezeiraud-play\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\gaeta\\\\.electron-gyp\\\\13.1.4\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\gaeta\\Git\\dezeiraud-play\\node_modules\\keytar',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\gaeta\\Git\\dezeiraud-play\\node_modules\\keytar\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
⠙ Building module: keytar, Completed: 0gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64',
gyp info spawn args   map: [Function (anonymous)]
gyp info spawn args ]
⠹ Building module: keytar, Completed: 0Les projets sont générés individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "-m".
⠦ Building module: keytar, Completed: 0  async.cc
⠋ Building module: keytar, Completed: 0C:\Users\gaeta\Git\dezeiraud-play\node_modules\keytar\node_modules\node-addon-api\napi-inl.h(1393,24): error C3861: 'napi_object_freeze': ident
ifier not found [C:\Users\gaeta\Git\dezeiraud-play\node_modules\keytar\build\keytar.vcxproj]
C:\Users\gaeta\Git\dezeiraud-play\node_modules\keytar\node_modules\node-addon-api\napi-inl.h(1399,24): error C3861: 'napi_object_seal': identif 
ier not found [C:\Users\gaeta\Git\dezeiraud-play\node_modules\keytar\build\keytar.vcxproj]
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild 'C:\Users\gaeta\Git\dezeiraud-play\node_modules\keytar'.
Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1



Error: node-gyp failed to rebuild 'C:\Users\gaeta\Git\dezeiraud-play\node_modules\keytar'.
Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1


    at ModuleRebuilder.rebuildNodeGypModule (C:\Users\gaeta\Git\dezeiraud-play\node_modules\electron-rebuild\lib\src\module-rebuilder.js:193:19)    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Rebuilder.rebuildModuleAt (C:\Users\gaeta\Git\dezeiraud-play\node_modules\electron-rebuild\lib\src\rebuild.js:190:9)
    at async Rebuilder.rebuild (C:\Users\gaeta\Git\dezeiraud-play\node_modules\electron-rebuild\lib\src\rebuild.js:152:17)
    at async C:\Users\gaeta\Git\dezeiraud-play\node_modules\electron-rebuild\lib\src\cli.js:146:9
```

Thanks.

**Comment by Brouilles** [comment]
I think it is the same issue https://github.com/atom/node-keytar/issues/399

**Comment by Ranjith-Eswaran-G** [comment]
@Brouilles , I am also facing the same issue. Did you get any work around to fix this?

**Comment by Brouilles** [comment]
I had found a solution. But I don't remember it sorry.
