### ISSUE TITLE
x64 binary on armv7l?

### ISSUE THREAD

**Issue by antiochtech** [atom/node-keytar#403]
project built on ubuntu 18 x64 for raspbios armv7l with keytar v7.7.0.

upon execution:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /usr/lib/project/resources/app/node_modules/keytar/build/Release/keytar.node: wrong ELF class: ELFCLASS64
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/lib/project/resources/app/node_modules/keytar/lib/keytar.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
```

**Comment by deibertf** [comment]
This may be related to #401

**Comment by antiochtech** [comment]
my `project/node_modules/keytar/bin` only includes a `linux-x64-89` directory. being sort of a newb, im not sure how im supposed to acquire and include binaries for other platforms and architectures?

**Comment by antiochtech** [comment]
finally got it. how do i contribute the armv7l version of the keytar.node file to the project?
