### ISSUE TITLE
Module version mismatch. Expected 50, got 51

### ISSUE THREAD

**Issue by idoshamun** [atom/node-keytar#54]
When trying to use keytar with node 7.1.0 in ubuntu 14.04, I get the following error:

```
Uncaught Exception:
Error: Module version mismatch. Expected 50, got 51.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:178:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:178:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/shamun/Development/Projects/firepaste/firepaste-desktop/node_modules/keytar/lib/keytar.js:4:12)
```

**Comment by idoshamun** [comment]
Using [electron-rebuild](https://github.com/electron/electron-rebuild) actually fixed the problem
