### ISSUE TITLE
can't install keytar on my system

### ISSUE THREAD

**Issue by HoffmannP** [atom/node-keytar#6]
system: `Linux Mint 16 Petra \n \l`
kernel: `3.11.0-12-generic`

Output

```
└━> LC_ALL='en_US.utf8' sudo npm install keytar
npm http GET https://registry.npmjs.org/keytar
npm http 304 https://registry.npmjs.org/keytar
npm http GET https://registry.npmjs.org/nan/0.8.0
npm http GET https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/nan/0.8.0

> keytar@1.0.0 install /home/ber/node_modules/keytar
> node-gyp rebuild

make: Entering directory `/home/ber/node_modules/keytar/build'
  CXX(target) Release/obj.target/keytar/src/main.o
make: g++: Command not found
make: *** [Release/obj.target/keytar/src/main.o] Error 127
make: Leaving directory `/home/ber/node_modules/keytar/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.11.0-12-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/ber/node_modules/keytar
gyp ERR! node -v v0.10.15
gyp ERR! node-gyp -v v0.10.9
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! keytar@1.0.0 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the keytar@1.0.0 install script.
npm ERR! This is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.11.0-12-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "keytar"
npm ERR! cwd /home/ber/Desktop
npm ERR! node -v v0.10.15
npm ERR! npm -v 1.2.18
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ber/Desktop/npm-debug.log
npm ERR! not ok code 0
```

I can send `npm-debug.log` by request

**Comment by joeferraro** [comment]
@zcbenz is there a specific version of g++ required? I keep getting the following when trying to build on Ubuntu 12:

```
> keytar@2.1.0 install /home/travis/build/joeferraro/mavensmate-app/app/node_modules/keytar
> node-gyp rebuild
make: Entering directory `/home/travis/build/joeferraro/mavensmate-app/app/node_modules/keytar/build'
  CXX(target) Release/obj.target/keytar/src/main.o
make: Leaving directory `/home/travis/build/joeferraro/mavensmate-app/app/node_modules/keytar/build'
npm WARN prefer global coffee-script@1.9.3 should be installed with -g
In file included from /home/travis/build/joeferraro/mavensmate-app/app/node_modules/electron-rebuild/lib/headers/.node-gyp/0.30.1/src/node.h:42:0,
                 from ../../nan/nan.h:24,
                 from ../src/main.cc:1:
/home/travis/build/joeferraro/mavensmate-app/app/node_modules/electron-rebuild/lib/headers/.node-gyp/0.30.1/deps/v8/include/v8.h:543:1: error: expected unqualified-id before ‘using’
/home/travis/build/joeferraro/mavensmate-app/app/node_modules/electron-rebuild/lib/headers/.node-gyp/0.30.1/deps/v8/include/v8.h:922:1: error: expected unqualified-id before ‘using’
make: *** [Release/obj.target/keytar/src/main.o] Error 1
```

**Comment by zcbenz** [comment]
@joeferraro The g++ needs to be >= 4.8, recent V8 versions require C++11 features to compile native modules.
