### ISSUE TITLE
Unhandled Rejection (TypeError): keytar.setPassword is not a function

### ISSUE THREAD

**Issue by frankolson** [atom/node-keytar#95]
I have an Electron + `create-react-app` application where I am attempting to store user passwords in the local keychain. However, when I run the `savePass` function from the following code:

```javascript
import keytar from 'keytar';

...

export const savePass = (savedKeyPairId, pass) => {
  return keytar.setPassword('Account', 'Service', pass);
}
```

I get the following error message:

```
Unhandled Rejection (TypeError): keytar.setPassword is not a function
```

Has anybody else run into this issue and/or know where I can start the debugging process?

**Comment by shiftkey** [comment]
@frankolson I think your import statement is off.

This is how we do the import in GitHub Desktop (it's TypeScript, but the rest should map to your code):

```ts
import * as keytar from 'keytar'

function setItem(key: string, login: string, value: string) {
  return keytar.setPassword(key, login, value)
}
```

**Comment by frankolson** [comment]
@shiftkey, after looking at the source [code](https://github.com/atom/node-keytar/blob/master/lib/keytar.js#L25), your suggestion definitely makes sense, thank you. Unfortunately, I am still getting the same error. I even logged the value of `keytar` to see what it was returning:

<img width="566" alt="screen shot 2018-01-19 at 7 54 58 am" src="https://user-images.githubusercontent.com/6773706/35159402-f9c9e48c-fcee-11e7-9457-6f5baaff119d.png">

That error actually points to [line 38 in `lib/keytar.js`](https://github.com/atom/node-keytar/blob/master/lib/keytar.js#L38) which is the return statement of the function being exported as `setPassword` inside the `keytar` package.

**Comment by lduros** [comment]
Hi:

I'm encountering the exact same issue, and I'm trying to load keytar inside the browser window, which I think might be a problem because it is an unprivileged context, compared to the script which creates the window. Correct me if this is a wrong assumption in Electron. In any case, keytar does not load in the electron-start script I have. Did you figure out how to solve this?

Thanks,

**Comment by gknapp** [comment]
I'm encountering this problem as well but for `findPassword`. Looking [at the source](https://github.com/atom/node-keytar/blob/master/lib/keytar.js#L51), it's as if the `require('../build/Release/keytar.node')` statement is failing within `lib\keytar.js`.

I've moved all my code interacting with `keytar` to my `main` electron thread and call it via IPC from the renderer thread.

```
  getPassword = (service) => {
    console.log("keytar", keytar);
    return keytar.findPassword(service);
  }
```
Output:
```
keytar { getPassword: [Function: getPassword],
  setPassword: [Function: setPassword],
  deletePassword: [Function: deletePassword],
  findPassword: [Function: findPassword],
  findCredentials: [Function: findCredentials] }
TypeError: keytar.findPassword is not a function
    at callback (webpack:///./node_modules/keytar/lib/keytar.js?:51:47)
    at eval (webpack:///./node_modules/keytar/lib/keytar.js?:12:7)
    at Promise (<anonymous>)
    at callbackPromise (webpack:///./node_modules/keytar/lib/keytar.js?:11:12)
    at Object.findPassword (webpack:///./node_modules/keytar/lib/keytar.js?:51:12)
    at exports.default.getPassword.service [as getPassword] (webpack:///./src/electron/main/store.js?:41:31)
    at EventEmitter.relayServerPassword (webpack:///./src/electron/main/ipc.js?:118:16)
    at emitTwo (events.js:125:13)
    at EventEmitter.emit (events.js:213:7)
    at WebContents.<anonymous>
```

**Comment by gknapp** [comment]
I've downgraded to 3.0.2 and switched from `import ... from` to `require()` syntax (possibly futile as I'm transpiling with babel), still encountering `keytar.findPassword is not a function`

**Comment by shiftkey** [comment]
@gknapp thanks for the extra details. If you've got an isolated repro of the issue to share that'd be great, but I'd also check that your webpack configuration is pulling in your native node modules. Here's an example of the loader we use in another Electron + webpack project that you might be missing:

https://github.com/desktop/desktop/blob/d338a73a3acbfbb5250d45863e19027fb73572b5/app/webpack.common.ts#L45-L51

**Comment by DnOberon** [comment]
any movement on this?

**Comment by saostad** [comment]
I have the same problem.
using Parcel, Rollup same error message.
`keytar.findCredentials is not a function`
changed the import statement from `import { findCredentials } from "keytar";` TO `import * as keytar from 'keytar'` didn't help.
